language: r
dist: trusty
sudo: true

branches:
  only:
    - dev
    - master

notifications:
  slack: insileco:bSFo4jHeKnaM4WobzJJ8DTPj


cache:
  packages: yes
  directories:
    - $HOME/bin

before_install:
  - sudo apt-get -qq update
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update
  - sudo apt-get install -y libgdal-dev libgeos-dev libproj-dev libudunits2-dev
  - sudo apt-get install -y libfreetype6-dev libpoppler-cpp-dev libssl-dev
  - mkdir pandoc
  - wget https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-1-amd64.deb
  - ls
  - pwd
  - sudo dpkg -i pandoc-1.19.2.1-1-amd64.deb ./pandoc
  - ls ~/pandoc/1.19
  - export PATH=/pandoc/usr/bin/:$PATH
  - type -p pandoc
  - pandoc --version

before_script:
  - "Rscript -e 'blogdown::install_hugo()'"
  - "Rscript pkgsList.R"

script:
  - "Rscript -e 'blogdown::build_site()'"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: master
  local_dir: public
  on:
    branch: dev
