language: r
dist: trusty
sudo: true

branches:
  only:
    - dev
    - master

notifications:
  slack: insileco:bSFo4jHeKnaM4WobzJJ8DTPj


cache:
  packages: yes
  directories:
    - $HOME/bin

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgdal-dev libgeos-dev libproj-dev

before_script:
  - "Rscript -e 'blogdown::install_hugo()'"
  - "Rscript pkgsList.R"

script:
  - "Rscript -e 'blogdown::build_site()'"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: master
  local_dir: public
  on:
    branch: dev
